services:

#  =================== Databases ===================

  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: andrzej
      POSTGRES_PASSWORD: zaq1@WSX
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=andrzej
      - MONGO_INITDB_ROOT_PASSWORD=andrzej


#  ================ Message Brokers ===============

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-net


  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1           # Replications
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1   # Replications
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181             # URL OF ZOOKEEPER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - microservices-net



#  ================ Mailer Service ================

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080 # UI
      - 1025:1025 # SMTP

#  ================= Monitoring ==================

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net


#  ================== Networks ===================
networks:
  microservices-net:
    driver: bridge

#  =================== Volumes ===================
volumes:
  postgres:
  pgadmin:
  mongo: